version: '3'
services:
  mongo:
    restart: always
    container_name: algernons-mongodb
    image: mongo
    environment:
     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITIAL_USERNAME}
     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITIAL_PASSWORD}
     MONGO_INITDB_DATABASE: ${MONGO_INITIAL_DATABASE} 
    volumes:
      - mongodata:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    environment:
      PORT: '${BACKEND_PORT}'
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITIAL_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITIAL_PASSWORD}
      MONGO_INITIAL_DATABASE: ${MONGO_INITIAL_DATABASE}
    depends_on:
      - mongo
    restart: always
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - '${ME_PORT}:${ME_PORT}'
    volumes:
      - mongodata:/data/db
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_CONTAINER_NAME}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMINPASSWORD}

volumes:
  mongodata:
    driver: local



