
services:
  mongo:
    restart: always
    container_name: algernons-mongodb
    image: mongo
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITIAL_USERNAME}
     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITIAL_PASSWORD}
     MONGO_INITDB_DATABASE: ${MONGO_INITIAL_DATABASE} 
    volumes:
      - mongodata:/data/db
      - ./backend/mongo-init/:/docker-entrypoint-initdb.d/:ro
    networks:
      - the_bat_cave
    env_file:
      - .env
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: the_back_end
    ports:
      - '1116:${BACKEND_PORT}'
    volumes:
        - ./backend:/app 
        - /app/node_modules
    environment:
      PORT: '${BACKEND_PORT}'
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITIAL_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITIAL_PASSWORD}
      MONGO_INITIAL_DATABASE: ${MONGO_INITIAL_DATABASE}
      MONGODB_CONN_STRING: ${MONGODB_CONN_STRING}
    depends_on:
      - mongo
    restart: always
    networks:
      - the_bat_cave
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - '7744:${ME_PORT}'
    volumes:
      - mongodata:/data/db
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_CONTAINER_NAME}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMINPASSWORD}
    networks:
      - the_bat_cave

volumes:
  mongodata:
    driver: local

networks:
  the_bat_cave:
    name: the_dark_knight
    driver: bridge
    



